### ISSUE TITLE
Raise exception instead of logging error

### ISSUE THREAD

**Issue by apirogov** [JenSte/aiotus#161]
In my project I integrate tusd with a http hook and I am trying to use aiotus in my test suite to test the hook (correct status codes/responses).

Unfortunately, only the log contains e.g. the status code returned by my hook that is passed on by `tusd` to aiotus, and capturing logs during testing is cumbersome. It would be great if `upload` would throw an exception instead of just logging the error silently.
A keyword argument to `upload` to make it throw would be great, without needing to change the default behaviour.

Thanks in advance!

**Comment by JenSte** [comment]
`aiotus.upload()` does retry in case of communication errors, and returns either a `yarl.URL` or `None`. The actual error that occurred is swallowed, this function is intended for the case where all you are interested in is if the upload succeeded or failed.

I think for your use case you could use the underlying functions that do the HTTP requests directly, they throw exceptions when errors happen:
```
with open(..., "rb") as fd:
    async with aiohttp.ClientSession() as session:
        location = await aiotus.creation.create(session, creation_url)
        await aiotus.core.upload_buffer(session, location, fd)
```

**Comment by apirogov** [comment]
Ok, thanks, I'll try that!
