### ISSUE TITLE
request: add aiofiles support.

### ISSUE THREAD

**Issue by rushkii** [JenSte/aiotus#307]
Instead of using the Python std file, you can use the aiofiles since the library using async method, aiofiles offer async that similar to Python std file.

In `aiotus/creation.py` on line 65, you can just use `aiofiles.open() as f: await f.seek()`

**Comment by JenSte** [comment]
> In `aiotus/creation.py` on line 65, you can just use `aiofiles.open() as f: await f.seek()`

It's not that simple, the `file` argument of that function is of type `BinaryIO`, nothing to re-open here, and `aiofiles` does not work with that type.

I knew about `aiofiles` when writing this code, but it does not seem worth it to justify adding another dependency. Just calling the blocking function in an executor is easy enough.

**Comment by rushkii** [comment]
> > In `aiotus/creation.py` on line 65, you can just use `aiofiles.open() as f: await f.seek()`
> 
> It's not that simple, the `file` argument of that function is of type `BinaryIO`, nothing to re-open here, and `aiofiles` does not work with that type.
> 
> I knew about `aiofiles` when writing this code, but it does not seem worth it to justify adding another dependency. Just calling the blocking function in an executor is easy enough.

Oh okay. If that so, can you add another upload method using `bytes` or `io.BytesIO()` ? for example:
```py
import aiotus

url = await aiotus.upload_from_bytes("endpoint", HERE_BYTES_OR_ARRAY_OF_BYTES)
```

**Comment by JenSte** [comment]
> Oh okay. If that so, can you add another upload method using `bytes` or `io.BytesIO()` ? for example:

`aiotus.upload` already supports `io.BytesIO`.
